# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24.2'

    - name: Test
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24.2'

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        BINARY_NAME=goirc
        if [ "$GOOS" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        OUTPUT_NAME="${BINARY_NAME}_${GOOS}_${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          OUTPUT_NAME="${OUTPUT_NAME}.exe"
        fi
        
        go build -v -ldflags="-s -w" -o "$OUTPUT_NAME" .
        
        # Create archive
        if [ "$GOOS" = "windows" ]; then
          zip "${OUTPUT_NAME%.exe}.zip" "$OUTPUT_NAME"
        else
          tar -czf "${OUTPUT_NAME}.tar.gz" "$OUTPUT_NAME"
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: goirc-${{ matrix.goos }}-${{ matrix.goarch }}
        path: |
          *.zip
          *.tar.gz

  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5

    - name: Generate version
      id: version
      run: |
        # Generate version based on date and short commit hash
        DATE=$(date +'%Y%m%d')
        SHORT_SHA=${GITHUB_SHA::7}
        VERSION="v${DATE}-${SHORT_SHA}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "tag=${VERSION}" >> $GITHUB_OUTPUT

    - name: Download all artifacts
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        files: |
          *.zip
          *.tar.gz
        draft: false
        prerelease: true
        generate_release_notes: true
        name: GoIRC ${{ steps.version.outputs.version }} (Pre-release)
        body: |
          ## GoIRC ${{ steps.version.outputs.version }} - Pre-release Build
          
          **⚠️ This is a pre-release build from the latest commit on main branch**
          
          **Commit:** ${{ github.sha }}
          **Build Date:** $(date +'%Y-%m-%d %H:%M:%S UTC')
          
          Cross-platform IRC client built with Go and Bubble Tea.
          
          ### Downloads
          
          **Linux:**
          - `goirc_linux_amd64.tar.gz` - Linux x64
          - `goirc_linux_arm64.tar.gz` - Linux ARM64
          
          **macOS:**
          - `goirc_darwin_amd64.tar.gz` - macOS Intel
          - `goirc_darwin_arm64.tar.gz` - macOS Apple Silicon
          
          **Windows:**
          - `goirc_windows_amd64.zip` - Windows x64
          
          ### Installation
          
          1. Download the appropriate archive for your platform
          2. Extract the binary
          3. Run `./goirc` (or `goirc.exe` on Windows)
          
          **Note:** Pre-release builds may contain experimental features and bugs. Use stable releases for production.
          
          Enjoy chatting on IRC! 🚀
